config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  resources :books
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image

  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
    @book = Book.new
  end

  def new
    @book = Book.new
  end

  def create
    @books = Book.all
    @book = Book.new(book_params)
    @book.save
    if @book.save
    flash[:notice] = "Book was successfully created."
    redirect_to book_path(@book.id)
    else
    render :index
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])

  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
     flash[:notice] = "Book was successfully updated."
    redirect_to book_path(@book.id)
    else
    render :edit
    end
  end

  def destroy
    @books = Book.all
    @book = Book.find(params[:id])
    @book.destroy
    flash[:alert] = "Book was successfully destroyed."
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<% if @book.errors.any? %>
  <%= @book.errors.count %> error prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book do |f| %>

  <p>Title</p><br>
  <%= f.text_field :title %><br>
<br>
  <p>Body</p><br>
  <%= f.text_area :body %><br>

<br>
  <span><%= f.submit 'Update Book' %></span><br>
<br>
<% end %>

    <%= link_to "Show", book_path(@book.id) %> ｜
    <%= link_to "Back", books_path %>

app/views/books/index.html.erb
  <div>
    <p><font color=”#008000”><%= flash[:alert] %></font></p>
  </div>

<h1>Books</h1>

<table class="table">
  <thead>
     <tr>
      <th class="header1">Title</th>
      <th class="header2">Body</th>
      <th class="header2"></th>
    </tr>
  </thead>

   <tbody>
     <% @books.each do |book| %><tr>
      <td><%= book.title %> </td>
      <td><%= book.body %></td>
      <td><%= link_to "Show", book_path(book.id) %></td>
      <td><%= link_to "Edit", edit_book_path(book.id) %></td>
      <td><%= link_to "Destroy", book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %></td>
  </span>
    </tr>
    <% end %>
  </tbody>
</table>




<h2>New book</h2>

<% if @book.errors.any? %>
  <%= @book.errors.count %> error prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: Book.new do |f| %>

  <a>Title</a><br>
  <%= f.text_field :title %>
<br>
<br>
  <a>Body</a><br>
  <%= f.text_area :body %><br>
<br>
  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/new.html.erb
<h2>New book</h2>

<%= form_with model: Book.new do |f| %>

  <a>Title</a><br>
  <%= f.text_field :title %>
<br>
<br>
  <a>Body</a><br>
  <%= f.text_area :body %><br>
<br>
  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<div class="text-success">
  <p><font color=”#008000”><%= flash[:notice] %></font></p>
</div>


<p><strong>Title: </strong><%= @book.title %></p>
<p><strong>Body: </strong><%= @book.body %></p>
  <span>
    <%= link_to "Edit", edit_book_path(@book.id) %> ｜
    <%= link_to "Back", "/books" %>
  </span>

app/views/homes/top.html.erb
<h1>ようこそ Bookers へ！</h1>

  <p><strong>Bookers</strong> では、様々な書籍に関するあなたの意見や</p>
  <p>印象を共有し交換することができます。</p>

  <p><%= link_to "start", "/books" %><p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
  </body>
</html>